project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  # - source: /versioned_docs/**/*
  #   translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%
  # - source: /src/pages/**/*
  #   translation: /i18n/%two_letters_code%/docusaurus-plugin-content-pages/**/%original_file_name%
  #   ignore: [/**/*.js, /**/*.jsx, /**/*.ts, /**/*.tsx, /**/*.css]
