name: Crowdin Action

on:
  # workflow_dispatch:
  push:
    branches: [ main ]

permissions: write-all

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin-action
        uses: crowdin/github-action@v1.19.0
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          # localization_branch_name: l10n_crowdin_translations
          # create_pull_request: true
          # pull_request_title: 'New Crowdin Translations'
          # pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          # pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Trigger deployment
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            "https://api.github.com/repos/scottafk/needle-docs/dispatches" \
            -d '{"event_type": "crowdin_finished"}'